version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./app:/usr/src/app/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jackson
      ME_CONFIG_BASICAUTH_PASSWORD: jackson
      ME_CONFIG_OPTIONS_EDITORTHEME: rubyblue
