POST http://localhost:3001/bookReveiws
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyQGphY2tzb24uY29tIiwiaWF0IjoxNjA1MDg1NzkzLCJleHAiOjE2MDUwODkzOTN9.5lJqawz7HBDWRGeTGzvbPfBEeqfFgS2YwGqmfmiXMm0
Content-Type: application/json

{
  "bookId": "5f8a85aa3ea55707a1b6a62b",
  "revieweeId": "5f8a84914411c507133637b4",
  "rating": "5",
  "review": "Good book"
}

DELETE http://localhost:3001/bookReveiws/5f8a87bd3cc5840845623212